Repository WithPeace/with-peace-android, pull requests merged in 2024-04, with the labels that each got.

#63 Feat/#43 프로필 기능을 개발한다
  app/build.gradle.kts
  app/src/main/java/com/withpeace/withpeace/WithpeaceApp.kt
  app/src/main/java/com/withpeace/withpeace/navigation/NavHost.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/mapper/ChangedProfileMapper.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/mapper/ProfileInfoMapper.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultTokenRepository.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultUserRepository.kt
  core/datastore/src/main/java/com/withpeace/withpeace/core/datastore/dataStore/DefaultTokenPreferenceDataSource.kt
  core/datastore/src/main/java/com/withpeace/withpeace/core/datastore/dataStore/TokenPreferenceDataSource.kt
  core/designsystem/src/main/java/com/withpeace/withpeace/core/designsystem/ui/TitleBar.kt
  core/designsystem/src/main/java/com/withpeace/withpeace/core/designsystem/ui/TopAppBar.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/WithPeaceErrorCode.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/profile/ChangedProfile.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/profile/ChangingProfileInfo.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/profile/Nickname.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/profile/ProfileChangingStatus.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/profile/ProfileInfo.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/repository/UserRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetProfileInfoUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/LogoutUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/UpdateProfileUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/VerifyNicknameUseCase.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/common/OkHttpUtil.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/common/WithPeaceErrorBody.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/di/ServiceModule.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/request/NicknameRequest.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/response/ChangedProfileResponse.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/response/ProfileResponse.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/service/AuthService.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/service/UserService.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/uistate/MyPageUiEvent.kt
  feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/uistate/ProfileInfoMapper.kt
  feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/uistate/ProfileInfoUiModel.kt
  feature/mypage/src/main/res/drawable/ic_default_profile.xml
  feature/mypage/src/main/res/values/strings.xml
  feature/profileeditor/.gitignore
  feature/profileeditor/build.gradle.kts
  feature/profileeditor/consumer-rules.pro
  feature/profileeditor/proguard-rules.pro
  feature/profileeditor/src/androidTest/java/com/app/profileeditor/ExampleInstrumentedTest.kt
  feature/profileeditor/src/main/AndroidManifest.xml
  feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorScreen.kt
  feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorViewModel.kt
  feature/profileeditor/src/main/java/com/app/profileeditor/ProfileModelMapper.kt
  feature/profileeditor/src/main/java/com/app/profileeditor/navigation/ProfileEditorNavigation.kt
  feature/profileeditor/src/main/java/com/app/profileeditor/uistate/ProfileEditUiEvent.kt
  feature/profileeditor/src/main/java/com/app/profileeditor/uistate/ProfileNicknameValidUiState.kt
  feature/profileeditor/src/main/java/com/app/profileeditor/uistate/ProfileUiModel.kt
  feature/profileeditor/src/main/res/drawable/ic_default_profile.xml
  feature/profileeditor/src/main/res/drawable/ic_editor_pencil.xml
  feature/profileeditor/src/main/res/values/strings.xml
  feature/profileeditor/src/test/java/com/app/profileeditor/ExampleUnitTest.kt
  settings.gradle.kts
Labels: Feature

#74 feat/#52 signup 기능을 구현한다
  app/build.gradle.kts
  app/src/main/java/com/withpeace/withpeace/WithpeaceApp.kt
  app/src/main/java/com/withpeace/withpeace/navigation/NavHost.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/mapper/RoleMapper.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultTokenRepository.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultUserRepository.kt
  core/datastore/src/main/java/com/withpeace/withpeace/core/datastore/dataStore/token/DefaultTokenPreferenceDataSource.kt
  core/datastore/src/main/java/com/withpeace/withpeace/core/datastore/dataStore/token/TokenPreferenceDataSource.kt
  core/datastore/src/main/java/com/withpeace/withpeace/core/datastore/dataStore/user/DefaultUserPreferenceDataSource.kt
  core/datastore/src/main/java/com/withpeace/withpeace/core/datastore/dataStore/user/UserPreferenceDataSource.kt
  core/datastore/src/main/java/com/withpeace/withpeace/core/datastore/di/DataStoreModule.kt
  core/datastore/src/main/java/com/withpeace/withpeace/core/datastore/di/PreferenceDataSourceModule.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/SignUpInfo.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/role/Role.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/repository/TokenRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/repository/UserRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/IsLoginUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/SignUpUseCase.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/IsLoginUseCaseTest.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/SignUpUseCaseTest.kt
  core/interceptor/src/main/java/com/withpeace/withpeace/core/interceptor/AuthInterceptor.kt
  core/interceptor/src/main/java/com/withpeace/withpeace/core/interceptor/InterceptorModule.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/request/SignUpRequest.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/response/LoginResponse.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/service/AuthService.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/service/UserService.kt
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/withpeace/withpeace/core/ui/profile/NicknameEditor.kt
  core/ui/src/main/java/com/withpeace/withpeace/core/ui/profile/ProfileEditor.kt
  core/ui/src/main/java/com/withpeace/withpeace/core/ui/profile/ProfileNicknameValidUiState.kt
  core/ui/src/main/res/drawable/ic_default_profile.xml
  core/ui/src/main/res/drawable/ic_editor_pencil.xml
  core/ui/src/main/res/values/strings.xml
  feature/login/src/main/java/com/withpeace/withpeace/feature/login/LoginScreen.kt
  feature/login/src/main/java/com/withpeace/withpeace/feature/login/LoginUiEvent.kt
  feature/login/src/main/java/com/withpeace/withpeace/feature/login/LoginViewModel.kt
  feature/login/src/main/java/com/withpeace/withpeace/feature/login/navigation/LoginNavigation.kt
  feature/login/src/test/java/com/withpeace/withpeace/feature/login/LoginViewModelTest.kt
  feature/profileeditor/build.gradle.kts
  feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorScreen.kt
  feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorViewModel.kt
  feature/profileeditor/src/main/res/values/strings.xml
  feature/signup/.gitignore
  feature/signup/build.gradle.kts
  feature/signup/consumer-rules.pro
  feature/signup/proguard-rules.pro
  feature/signup/src/androidTest/java/com/withpeace/withpeace/feature/signup/ExampleInstrumentedTest.kt
  feature/signup/src/main/AndroidManifest.xml
  feature/signup/src/main/java/com/withpeace/withpeace/feature/signup/SignUpMapper.kt
  feature/signup/src/main/java/com/withpeace/withpeace/feature/signup/SignUpScreen.kt
  feature/signup/src/main/java/com/withpeace/withpeace/feature/signup/SignUpViewModel.kt
  feature/signup/src/main/java/com/withpeace/withpeace/feature/signup/navigation/SignUpNavigation.kt
  feature/signup/src/main/java/com/withpeace/withpeace/feature/signup/uistate/SignUpUiEvent.kt
  feature/signup/src/main/java/com/withpeace/withpeace/feature/signup/uistate/SignUpUiModel.kt
  feature/signup/src/main/res/drawable/app_logo.png
  feature/signup/src/main/res/values/strings.xml
  feature/signup/src/test/java/com/withpeace/withpeace/feature/signup/ExampleUnitTest.kt
  settings.gradle.kts
Labels: Feature

#80 fix: 헤더 변경
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/service/AuthService.kt
Labels: bug

#79 Feat/#67 게시글 목록 기능 구현
  app/src/main/java/com/withpeace/withpeace/MainBottomNavigation.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/mapper/DateMapper.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/mapper/PostMapper.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/mapper/PostTopicMapper.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultPostRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/post/PostPageInfo.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/paging/PostPagingSource.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/repository/PostRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetPostsUseCase.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/response/post/PostIdResponse.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/response/post/PostResponse.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/response/post/PostTopicResponse.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/service/PostService.kt
  core/ui/src/main/java/com/withpeace/withpeace/core/ui/PostTopicUiState.kt
  core/ui/src/main/java/com/withpeace/withpeace/core/ui/post/PostUiModel.kt
  feature/postlist/build.gradle.kts
  feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
  feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListUiEvent.kt
  feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListViewModel.kt
  feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/TopicTabs.kt
  feature/profileeditor/src/test/java/com/app/profileeditor/ExampleUnitTest.kt
  feature/signup/src/main/AndroidManifest.xml
  settings.gradle.kts
Labels: Feature

#86 Fix/#76 프로필 최초 로그인 qa 사안 적용한다
  app/src/main/java/com/withpeace/withpeace/MainBottomNavigation.kt
  app/src/main/java/com/withpeace/withpeace/navigation/NavHost.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/profile/Nickname.kt
  core/interceptor/src/main/java/com/withpeace/withpeace/core/interceptor/AuthInterceptor.kt
  core/ui/src/main/java/com/withpeace/withpeace/core/ui/profile/NicknameEditor.kt
  core/ui/src/main/java/com/withpeace/withpeace/core/ui/profile/ProfileNicknameValidUiState.kt
  feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorScreen.kt
  feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorViewModel.kt
Labels: bug

#88 Refactor/#87 오류처리 개선
  app/src/main/java/com/withpeace/withpeace/navigation/NavHost.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultPostRepository.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultTokenRepository.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultUserRepository.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/util/ApiResponseExtension.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/Response.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/WithPeaceError.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/WithPeaceErrorCode.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/error/CheonghaError.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/error/ClientError.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/error/ResponseError.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/paging/PostPagingSource.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/repository/PostRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/repository/TokenRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/repository/UserRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/DeletePostUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetPostDetailUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetPostsUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetProfileInfoUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GoogleLoginUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/LogoutUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/RegisterPostUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/SignUpUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/UpdateProfileUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/VerifyNicknameUseCase.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/GoogleLoginUseCaseTest.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/RegisterPostUseCaseTest.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/SignUpUseCaseTest.kt
  feature/login/src/main/java/com/withpeace/withpeace/feature/login/LoginViewModel.kt
  feature/login/src/test/java/com/withpeace/withpeace/feature/login/LoginViewModelTest.kt
  feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/uistate/MyPageUiEvent.kt
  feature/postdetail/src/main/java/com/withpeace/withpeace/feature/postdetail/PostDetailScreen.kt
  feature/postdetail/src/main/java/com/withpeace/withpeace/feature/postdetail/PostDetailUiEvent.kt
  feature/postdetail/src/main/java/com/withpeace/withpeace/feature/postdetail/PostDetailUiState.kt
  feature/postdetail/src/main/java/com/withpeace/withpeace/feature/postdetail/PostDetailViewModel.kt
  feature/postdetail/src/main/java/com/withpeace/withpeace/feature/postdetail/navigation/PostDetailNavigation.kt
  feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
  feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListViewModel.kt
  feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/navigation/PostListNavigation.kt
  feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorScreen.kt
  feature/profileeditor/src/main/java/com/app/profileeditor/ProfileEditorViewModel.kt
  feature/profileeditor/src/main/java/com/app/profileeditor/navigation/ProfileEditorNavigation.kt
  feature/registerpost/src/main/java/com/withpeace/withpeace/feature/registerpost/RegisterPostScreen.kt
  feature/registerpost/src/main/java/com/withpeace/withpeace/feature/registerpost/RegisterPostUiEvent.kt
  feature/registerpost/src/main/java/com/withpeace/withpeace/feature/registerpost/navigation/RegisterPostNavigation.kt
  feature/registerpost/src/test/java/com/withpeace/withpeace/feature/registerpost/RegisterPostViewModelTest.kt
  feature/signup/src/main/java/com/withpeace/withpeace/feature/signup/SignUpViewModel.kt
Labels: Refactoring

#89 Paging 성능 개선 및 테스트 작성
  core/data/build.gradle.kts
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/paging/ImagePagingSource.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/paging/PostPagingSource.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultImageRepository.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultPostRepository.kt
  core/data/src/test/kotlin/com/withpeace/withpeace/core/data/paging/ImagePagingSourceTest.kt
  core/data/src/test/kotlin/com/withpeace/withpeace/core/data/paging/PostPagingSourceTest.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/image/ImagePagingInfo.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/post/PostPageInfo.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/paging/PostPagingSource.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/repository/ImageRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/repository/PostRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetAlbumImagesUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GetPostsUseCase.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/GetAlbumImagesUseCaseTest.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/GetPostsUseCaseTest.kt
  core/ui/src/main/java/com/withpeace/withpeace/core/ui/DateUiModel.kt
  feature/gallery/src/main/java/com/withpeace/withpeace/feature/gallery/GalleryScreen.kt
  feature/gallery/src/main/java/com/withpeace/withpeace/feature/gallery/GalleryViewModel.kt
  feature/gallery/src/test/java/com/withpeace/withpeace/feature/gallery/GalleryViewModelTest.kt
  feature/postdetail/src/main/java/com/withpeace/withpeace/feature/postdetail/PostDetailScreen.kt
  feature/postlist/build.gradle.kts
  feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListScreen.kt
  feature/postlist/src/main/java/com/withpeace/withpeace/feature/postlist/PostListViewModel.kt
  feature/postlist/src/test/java/com/withpeace/withpeace/feature/postlist/ExampleUnitTest.kt
  feature/postlist/src/test/java/com/withpeace/withpeace/feature/postlist/PostListViewModelTest.kt
Labels: Refactoring
