Repository WithPeace/with-peace-android, pull requests merged in 2024-03, with the labels that each got.

#44 feat : 에러함수 콜백으로 처리 및 Interceptor retrofit을 이용하도록 수정
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/mapper/TokenMapper.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultTokenRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/AuthToken.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/repository/AuthTokenRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GoogleLoginUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/IsLoginUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/SignUpUseCase.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/GoogleLoginUseCaseTest.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/IsLoginUseCaseTest.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/SignUpUseCaseTest.kt
  core/interceptor/build.gradle.kts
  core/interceptor/src/main/java/com/withpeace/withpeace/core/interceptor/AuthInterceptor.kt
  core/interceptor/src/main/java/com/withpeace/withpeace/core/interceptor/InterceptorModule.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/AuthInterceptor.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/di/NetworkModule.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/di/ServiceModule.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/service/AuthService.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/service/UserService.kt
  feature/login/src/main/java/com/withpeace/withpeace/feature/login/LoginViewModel.kt
  feature/login/src/test/java/com/withpeace/withpeace/feature/login/LoginViewModelTest.kt
Labels: Refactoring

#46 Feat/#45 UI 비율을 360800 수정
  feature/login/src/main/java/com/withpeace/withpeace/feature/login/LoginScreen.kt
Labels: Refactoring

#48 Feat/#38 401 로직 구현
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/mapper/TokenMapper.kt
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultTokenRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/AuthToken.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/Response.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/model/WithPeaceError.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/repository/AuthTokenRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/repository/TokenRepository.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/GoogleLoginUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/IsLoginUseCase.kt
  core/domain/src/main/java/com/withpeace/withpeace/core/domain/usecase/SignUpUseCase.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/GoogleLoginUseCaseTest.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/IsLoginUseCaseTest.kt
  core/domain/src/test/kotlin/com/withpeace/withpeace/core/domain/usecase/SignUpUseCaseTest.kt
  feature/login/src/main/java/com/withpeace/withpeace/feature/login/LoginViewModel.kt
  feature/login/src/test/java/com/withpeace/withpeace/feature/login/LoginViewModelTest.kt
Labels: Refactoring

#50 refactor: googleLogin Response 수정
  core/data/src/main/kotlin/com/withpeace/withpeace/core/data/repository/DefaultTokenRepository.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/response/LoginResponse.kt
  core/network/src/main/java/com/withpeace/withpeace/core/network/di/service/AuthService.kt
Labels: bug, Refactoring

#55 Feat/#53 바텀 네비게이션을 구현한다
  app/build.gradle.kts
  app/src/main/java/com/withpeace/withpeace/MainActivity.kt
  app/src/main/java/com/withpeace/withpeace/MainBottomNavigation.kt
  app/src/main/java/com/withpeace/withpeace/WithpeaceApp.kt
  app/src/main/java/com/withpeace/withpeace/navigation/NavHost.kt
  app/src/main/res/drawable/ic_bottom_home.xml
  app/src/main/res/drawable/ic_bottom_home_select.xml
  app/src/main/res/drawable/ic_bottom_my_page.xml
  app/src/main/res/drawable/ic_bottom_my_page_select.xml
  app/src/main/res/drawable/ic_bottom_post.xml
  app/src/main/res/drawable/ic_bottom_post_register.xml
  app/src/main/res/drawable/ic_bottom_post_select.xml
  app/src/main/res/values/strings.xml
  feature/home/.gitignore
  feature/home/build.gradle.kts
  feature/home/consumer-rules.pro
  feature/home/proguard-rules.pro
  feature/home/src/androidTest/java/com/withpeace/withpeace/feature/home/ExampleInstrumentedTest.kt
  feature/home/src/main/AndroidManifest.xml
  feature/home/src/main/java/com/withpeace/withpeace/feature/home/HomeScreen.kt
  feature/home/src/main/java/com/withpeace/withpeace/feature/home/navigation/HomeNavigation.kt
  feature/home/src/test/java/com/withpeace/withpeace/feature/home/ExampleUnitTest.kt
  feature/mypage/.gitignore
  feature/mypage/build.gradle.kts
  feature/mypage/consumer-rules.pro
  feature/mypage/proguard-rules.pro
  feature/mypage/src/androidTest/java/com/withpeace/withpeace/feature/mypage/ExampleInstrumentedTest.kt
  feature/mypage/src/main/AndroidManifest.xml
  feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/withpeace/withpeace/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/test/java/com/withpeace/withpeace/feature/mypage/ExampleUnitTest.kt
  feature/post/.gitignore
  feature/post/build.gradle.kts
  feature/post/consumer-rules.pro
  feature/post/proguard-rules.pro
  feature/post/src/androidTest/java/com/withpeace/withpeace/feature/post/ExampleInstrumentedTest.kt
  feature/post/src/main/AndroidManifest.xml
  feature/post/src/main/java/com/withpeace/withpeace/feature/post/PostScreen.kt
  feature/post/src/main/java/com/withpeace/withpeace/feature/post/navigation/PostNavigation.kt
  feature/post/src/test/java/com/withpeace/withpeace/feature/post/ExampleUnitTest.kt
  settings.gradle.kts
Labels: Feature
